version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg14
    environment:
      POSTGRES_DB: rag_chatbot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  backend:
    build: ./rag_chatbot
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/rag_chatbot
      DJANGO_SETTINGS_MODULE: rag_chatbot.settings
      POSTGRES_DB: rag_chatbot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      - db
    ports:
      - "8000:8000" # Expose backend port for internal communication

  frontend:
    build: ./chatbot-qa-rag-frontend
    environment:
      REACT_APP_API_URL: http://backend:8000/api
    depends_on:
      - backend
    ports:
      - "3000:3000" # Expose frontend port to host

volumes:
  postgres_data: